name: Check That Code Compiles For Peter

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - main
      - develop

  pull_request_target:
    branches:
      - main
      - develop

jobs: 
  check-code-compilation:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Run Server
        run: npm run build


